material : menu.pngのサイズ変更
kathmandu777/i-make pull request #114
Opened 2022-10-06 15:21 UTC by itomo2

# Overview 

# Issue number 
Close #

# How to check the revision
1. 

# Points for Review 

# Remarks

2022-10-06 15:32 UTC, kathmandu777 requested changes
これ指定したサイズになってる？

2022-10-06 15:49 UTC, itomo2 commented
960*150になってると思います

2022-10-07 00:13 UTC, kathmandu777 commented
#116 で修正する
原因は、png, jpgの混同

2022-10-07 00:13 UTC, closed without merging

2022-10-07 01:47 UTC, itomo2 commented
すみません…まじですみません