Projector irradiation
kathmandu777/i-make pull request #24
Opened 2022-08-26 16:45 UTC by GoRuGoo

# Overview 

# Issue number 
Close #19

# How to check the revision
おまかせします

# Points for Review 
- メイクのみ投影できるかどうか
- docstringがしっかりと記述できているかどうか

# Remarks

2022-08-29 00:34 UTC, kathmandu777 requested changes
動作未検証。コードベースでのみの確認。

2022-08-29 00:34 UTC, kathmandu777 commented on gen2-facemesh/main_depthai_camera.py
> +            break
このマークが出ないようにpre-commitで補正をしています。
#23 の解決方法が今のところわかっていないので、ruby, gemなどをインストールして、pre-commitを走らせてみてください。

2022-08-29 00:34 UTC, kathmandu777 commented on gen2-facemesh/utils/effect.py
> +from this import d
？？

2022-08-29 00:34 UTC, kathmandu777 commented on gen2-facemesh/utils/effect_base.py
> +from typing import Tuple
_base.py に切り分けている必要はありますか？

2022-08-29 00:34 UTC, kathmandu777 commented on gen2-facemesh/utils/effect.py
> +        switch_only_make = True
initializeでこの変数は確定させたくないです。関数の引数として毎回指定したいです。

2022-08-29 00:34 UTC, kathmandu777 commented on gen2-facemesh/utils/effect.py
> +    def render_make_both(self, target_image: np.ndarray, target_landmarks: np.ndarray) -> np.ndarray:
関数の名前はそのままでOK
上に書いたように、ここでメイクのみか、顔にoverlayしたものにするかを引数で分岐する

2022-08-29 00:34 UTC, kathmandu777 commented on gen2-facemesh/utils/effect.py
> +        if self.switch_make_or_both:
switch_make_or_bothはなんか変な気がします。
`do_overlay` とかはどうでしょうか？

2022-08-29 00:34 UTC, kathmandu777 commented on gen2-facemesh/utils/effect.py
> +        if self.switch_make_or_both:
なぜ変な気がするかというと、orを使ってしまうと、Trueの時にどちらが選択されるかがわからないからです。

2022-08-29 00:34 UTC, kathmandu777 commented on gen2-facemesh/main_web_camera_base.py
> +#!/usr/bin/env python3
_base.pyに切り出されている理由はありますか？

2022-08-29 05:02 UTC, GoRuGoo commented
修正したものをpushしました

2022-08-29 05:08 UTC, GoRuGoo commented
このコード、gen2-facemesh下に作ってしまいましたが本番用なのでi-make下に移したほうがいいかもしれませんね...

2022-08-29 13:45 UTC, kathmandu777 commented
@GoRuGoo

> gen2-facemesh下に作ってしまいましたが本番用なのでi-make下に移したほうがいいかもしれませんね

お願いします。

2022-08-29 13:47 UTC, kathmandu777 commented
@GoRuGoo 
こみっとがきたなくなっているので、スカッシュしてほしいです

2022-08-29 15:25 UTC, GoRuGoo commented
ローカルでrebase -i を使ってまとめました、どうやってリモートと同期すればいいでしょうか？

2022-08-30 03:23 UTC, GoRuGoo commented
@kathmandu777

2022-08-30 03:24 UTC, kathmandu777 commented
Force pushでよきよ🙆‍♀️
@GoRuGoo

2022-08-30 08:37 UTC, GoRuGoo commented
２つにスカッシュしました、再レビューおねがいします

2022-08-30 13:33 UTC, kathmandu777 requested changes
動作は確認していない。
commitはもっと綺麗にできると思います。

2022-08-30 13:33 UTC, kathmandu777 commented on gen2-facemesh/main_depthai_camera.py
> +        cv2.imshow("Demo", applied_effect)
ここは、もとのままでいいのでは？
直接関係ない変更は含めないようにしてほしい！

2022-08-30 13:33 UTC, kathmandu777 commented on i-make/__main__.py
> +
これって必須ですか？

2022-08-30 13:33 UTC, kathmandu777 commented on i-make/__main__.py
> +"""
これは不要です。

2022-08-30 13:33 UTC, kathmandu777 commented on i-make/__main__.py
> +        cv2.imshow("RESULT", effected_image_second)
ここがよくわかんなーい

2022-08-30 13:33 UTC, kathmandu777 commented on i-make/libs/effect.py
> +        filter_points_path: str = "./res/filter_points.npy",
俺が記述した手順通りにやったら、パスの変更いらなくない？
できる限り不要な変更はコミットしないでほしい！

2022-08-30 13:33 UTC, kathmandu777 commented on i-make/libs/effect.py
> +            filter_points_path (str, optional): path to the filter landmarks. Defaults to "./res/filter_points.npy".
ditto

2022-08-30 13:33 UTC, kathmandu777 commented on i-make/libs/effect.py
> +            do_overlay (_type_): メイクを被せるか否か、Trueで被せる
```
メイクを元画像(target_image)の上に貼り付けるかどうか
```
にしましょうか

2022-08-30 13:33 UTC, kathmandu777 commented on i-make/libs/effect.py
> +        or pasted.
> and sorting between make-up only    or pasted.
なんか違和感のある英語な気がします。

元のままでもOKです。

2022-08-30 13:37 UTC, kathmandu777 commented
@GoRuGoo 
```
fix: add launch.json to .gitignore
```
これがわかれているのはGOOD！

```
add: Basic functionality implementation completed, only docstrings an…
```
このコミットに `pre-commit-config.yml` の修正が含まれちゃってるけど、できれば分けてほしかった！

2022-08-30 13:38 UTC, kathmandu777 commented
とりあえず、wipコミットがそのままなのは良くない状況やね
上に書いた以外のやつは一つのコミットにまとめてもいいよ！

2022-08-31 11:56 UTC, GoRuGoo commented on gen2-facemesh/main_depthai_camera.py
> +        cv2.imshow("Demo", applied_effect)
画像と、貼り付ける前のメイクは要素数が違うのでnp.hstackでは弾かれてしまいます。
貼り付ける前、貼り付けた後、両方に対応するための記述です

2022-08-31 11:57 UTC, GoRuGoo commented on i-make/__main__.py
> +        cv2.imshow("RESULT", effected_image_second)
ここは倍率変更機能を追加したところです、そのままのメイクは大きさが小さいので

2022-09-01 11:28 UTC, kathmandu777 approved these changes
LGTM!
Thanks!!

2022-09-01 11:29 UTC, merged