Part color change
kathmandu777/i-make pull request #45
Opened 2022-09-14 08:31 UTC by GoRuGoo

# Overview 

# Issue number 
Close #38 

# How to check the revision
1. 

# Points for Review 

# Remarks

2022-09-14 08:32 UTC, GoRuGoo commented
とりあえず部分的に動くか確認お願いします、
組み込みはそれが終わってから

2022-09-14 13:22 UTC, GoRuGoo commented
HSVのtype hintsにintと書きましたがfloatでも大丈夫そうです

2022-09-15 00:30 UTC, kathmandu777 requested changes
確認よろしくお願いします。

2022-09-15 00:30 UTC, kathmandu777 commented on i-make/test.py
> +def convert_make_color(
どのように convert されるか不明瞭かな

2022-09-15 00:30 UTC, kathmandu777 commented on i-make/test.py
> +    image: np.ndarray, h_ch: int, s_ch: int, v_ch: int, return_include_alphachannel: bool
Hue、Saturation or Sat, Value or Val のほうが良さそう
return_include_alphachannel -> include_alpha_ch とかで良さそう。 alpha と channel は区切る。 return はなんか違和感。

2022-09-15 00:30 UTC, kathmandu777 commented on i-make/test.py
> +        return_include_alphachannel(_type_):returnする画像にアルファチャンネルを含むか否か
Returnが書かれてないね

2022-09-15 00:30 UTC, kathmandu777 commented on i-make/test.py
> +    delete_alpha_image, mask = convert_rgba_to_rgb(image, True)
delete_alpha_image -> image_wo_alpha とかのうほうがわかりやすい。 wo = without (英語では、 w/, w/o みたいなかんじで、with, withoutを略します。たしか。)

2022-09-15 00:30 UTC, kathmandu777 commented on i-make/test.py
> +    hsv[:, :, 2] = np.where(hsv[:, :, 2] != 0, (v_ch * (hsv[:, :, 2] / 255)), hsv[:, :, 2])
ここの処理が正しいかはわかんないです

2022-09-15 00:30 UTC, kathmandu777 commented on i-make/test.py
> +    hsv = cv2.cvtColor(delete_alpha_image, cv2.COLOR_BGR2HSV)
hsv -> image_hsv みたいにしよう。hsvだと何なのかわからないかな。hsvのタプルとかと混同しやすい。
RGB画像は image_rgb とかにしてもいいね

2022-09-15 00:30 UTC, kathmandu777 commented on i-make/test.py
> +    bgr = cv2.cvtColor(hsv, cv2.COLOR_HSV2BGR)
ditto

2022-09-15 00:30 UTC, kathmandu777 commented on i-make/test.py
> +        include_alpha_bgr_image = cv2.merge((b_ch, g_ch, r_ch, mask))
image_bgr_w_alpha とかかな

2022-09-15 07:32 UTC, GoRuGoo commented
変にスカッシュしてレビューしにくくなっても申し訳ないので、最後にスカッシュします

2022-09-16 23:38 UTC, kathmandu777 commented
@GoRuGoo 
まず最初に、前回レビュー時のコミットを消し飛ばさないでほしいです。
差分がわからないのと、俺がどこにレビューしたかの情報が見えにくくなってしまうからです。

2022-09-16 23:43 UTC, kathmandu777 requested changes

2022-09-16 23:43 UTC, kathmandu777 commented on i-make/test.py
> +        np.array:任意の色、設定に変更したメイクのnumpy配列
型は `np.ndarray` かな？
np.array は listなどを np.ndarray にする関数です

2022-09-16 23:43 UTC, kathmandu777 commented on i-make/test.py
> +return_make = convert_make_hsvcolor(image, 240, 119.85, 163.2, True)
int 指定なのに、float入っているけどこれはいいの？？

2022-09-16 23:43 UTC, kathmandu777 commented on i-make/test.py
> +def convert_make_hsvcolor(
make ってかいてあるけど、それは俺らがmakeup画像を入れるという利用方法なだけで、関数としては画像をhsvに変換するだけなので、 `convert_rgb_to_hsv` or `convert_img_rgb_to_hsv` のほうがいいかな。

2022-09-16 23:43 UTC, kathmandu777 commented on i-make/test.py
> +        _type_: RGB imageもしくは
もしくは ... ??

2022-09-17 07:52 UTC, GoRuGoo commented on i-make/test.py
> +def convert_make_hsvcolor(
rgbをhsvにコンバートするわけでは無く、bgrをhsvにして色変更してhsvをbgrにして返却するのでconvert_color_bgraでいいかもしれません

2022-09-17 23:22 UTC, GoRuGoo commented
#47 に引き継ぐため一回マージします

2022-09-21 11:20 UTC, kathmandu777 commented on i-make/test.py
> +def convert_make_hsvcolor(
たしかに！
`convert_image_color` でいいかも
いい逆レビュー！！

2022-10-04 05:04 UTC, closed without merging