fix: 色変更関数の変数名などをわかりやすいようにした
kathmandu777/i-make pull request #60
Opened 2022-09-28 12:43 UTC by GoRuGoo

# Overview 
わかりやすいようにしたつもりです

# Issue number 
Close #

# How to check the revision
1. 

# Points for Review 

# Remarks

2022-09-28 12:52 UTC, kathmandu777 requested changes

2022-09-28 12:52 UTC, kathmandu777 commented on i-make/mode/base.py
> +        ]
もとの場所のままでお願いします

2022-09-28 12:52 UTC, kathmandu777 commented on i-make/mode/base.py
> +        """アルファチャンネル付きのHSV=(240,255,255)の画像の色を、指定したHSV数値の色に変更する.
元のコメントのままで良いんじゃないかな？

2022-09-28 12:52 UTC, kathmandu777 commented on i-make/mode/base.py
> +            image (_type_): H:240 S:255 V:255で塗りつぶしたアルファチャンネルを含むメイク素材、1024x1024
ditto

2022-09-28 12:52 UTC, kathmandu777 commented on i-make/mode/base.py
> +            val (_type_): HSVのValueの数値(0~255)
0~255で制限するならvalidationつけてもいいかも
範囲外でもおかしくならないならばそのままでも大丈夫
（たしかこの前口頭レビューしたところ）

2022-09-28 12:52 UTC, kathmandu777 commented on i-make/mode/base.py
> +        NOT_DETECT_VAL_VAL = 0
`VAL_VAL` になっちゃうから、最後のVALは不要です

2022-09-28 12:52 UTC, kathmandu777 commented on i-make/mode/base.py
> +        NOT_DETECT_VAL_VAL = 0
RGB=(0,0,255) ⇔ HSV=(120, 255, ?) っていう認識でいいかな？
それならば、
```
B255_HUE = 120
B255_SAT = 255
NO_CAHNGE_VAL = 0
```
みたいな感じ？？

認識違ったらごめん

2022-09-28 13:16 UTC, kathmandu777 requested changes

2022-09-28 13:16 UTC, kathmandu777 commented on i-make/mode/base.py
> +        if not ((0.0 <= hue <= 255) & (0.0 <= sat <= 255) & (0.0 <= val <= 255)):
あんどは記号ではなくローマ字じゃないとダメな気がする

2022-09-28 13:16 UTC, kathmandu777 commented on i-make/mode/base.py
> +            raise ValueError("Defferent range of values")
つづりが違う気がします

2022-09-28 13:16 UTC, kathmandu777 commented on i-make/mode/base.py
> +            raise ValueError("Defferent range of values")
1個ずつ判定した方が、どの値が範囲外かわかるからいい気がする

2022-09-28 14:25 UTC, kathmandu777 commented
@GoRuGoo 
俺だったらこんな感じにするかな

2022-09-28 15:24 UTC, GoRuGoo commented
一応そうなんですけど、B255で伝えて間違ったものが帰ってきたので…
けど欲しいのはbgraなんだよなぁ…
両方書くのがいいのでしょうか

2022-09-29 01:30 UTC, kathmandu777 commented
プログラム的には、B255を変換しているので、そのままで行きましょう

2022-09-29 14:43 UTC, merged